ublox_gps_node:
  ros__parameters:
    device: "/dev/ttyACM?"
    frame_id: "gps"
    config_on_startup: false
    tmode3: 0
    dgnss_mode: 3
    uart1:
      baudrate: 115200
      in: 7 
      out: 7 
    publish:
      nav:
        pvt: true
        pose: true